### ISSUE TITLE
PostgreSQL 9.5 branch changes pushdown quals?

### ISSUE THREAD

**Issue by robe2** [adunstan/file_text_array_fdw#2]
@adunstan this may be more of a question than a bug report.

I see you made a change in 9.5 stable branch - https://github.com/adunstan/file_text_array_fdw/commit/bbf91a1e00b60c8bc358f21cb2be71a96f9e7d44 to support push down quals.

This doesn't compile with my 9.5beta1 source.  Fixes I did for example to ogr_fdw only added the custom_tlist.  Is this another change coming like in 9.5rc or just a mistake (and should have only been committed to master branch? ).

https://github.com/pramsey/pgsql-ogr-fdw/commit/c065c6d46d2f8baa829f5ca036af8d662d0f4b34

**Comment by adunstan** [comment]
It's changed in git. See http://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=5043193b78919a1bd144563aadc2f7f726549913
