### ISSUE TITLE
Can't build with Fedora 38

### ISSUE THREAD

**Issue by mccuskk** [adunstan/file_text_array_fdw#5]
Trying to build RE_16_STABLE under fedora 38 gives the following error

file_textarray_fdw.c:1112:5: error: incompatible integer to pointer conversion passing 'Datum' (aka 'unsigned long') to parameter of type 'const void *' [-Wint-conversion]
                                DirectFunctionCall1(textin, 
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/pgsql-16/include/server/fmgr.h:643:2: note: expanded from macro 'DirectFunctionCall1'
        DirectFunctionCall1Coll(func, InvalidOid, arg1)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/pgsql-16/include/server/postgres.h:322:29: note: passing argument to parameter 'X' here
PointerGetDatum(const void *X)
                            ^
1 error generated.
make: *** [/usr/pgsql-16/lib/pgxs/src/makefiles/../../src/Makefile.global:1080: file_textarray_fdw.bc] Error 1
[

**Comment by adunstan** [comment]
Should be fixed in ef96459f34
